name: CI

on:
  push:
    branches:
    - mainstream
    - release/*
  pull_request:
    branches:
    - mainstream
    - release/*

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Debug Cecilia.sln
    - name: Test
      run: dotnet test --no-build -c Debug Cecilia.sln
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Debug Cecilia.sln
    - name: Test
      run: dotnet test --no-build --framework net6.0 -c Debug Cecilia.sln
