name: CI

on:
  push:
    branches:
    - mainstream
    - release/*
  pull_request:
    branches:
    - mainstream
    - release/*

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Debug Cecilia.sln
    - name: Test
      run: dotnet test --no-build -c Debug Cecilia.sln
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Debug Cecilia.sln
    - name: Test .NET Core
      run: dotnet test --no-build --framework net6.0 -c Debug Cecilia.sln
    - name: Get NuGet
      run: curl -o ./nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - name: Get NUnit.Console
      run: mono ./nuget.exe install NUnit.Console -Version 3.14.0 -OutputDirectory ./packages
    - name: Test .NET 4.0 using Mono
      run: mono ./packages/NUnit.ConsoleRunner.3.14.0/tools/nunit3-console.exe ./Cecilia.nunit
